import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from 'ui'
import { Footer } from "@/components/Footer";
import { Providers } from "@/providers";
import { Button } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar 
            actionButtons={
              <Button variant='contained' color='primary' >Login</Button>
            }
          />
          {children}
          <Footer/ >
        </Providers>
      </body>
    </html>
  );
}
